# Generated by Django 5.2.2 on 2025-06-12 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('codigo_interno', models.CharField(max_length=50, unique=True, verbose_name='Código Interno')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('unidade_medida', models.CharField(choices=[('m²', 'Metro Quadrado (m²)'), ('kg', 'Quilograma (kg)'), ('par', 'Par'), ('un', 'Unidade')], max_length=3, verbose_name='Unidade de Medida')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
            },
        ),
        migrations.CreateModel(
            name='PlanoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('codigo_plano', models.CharField(max_length=20, unique=True, verbose_name='Código do Plano')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('data_prevista_entrega', models.DateField(verbose_name='Data Prevista de Entrega')),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Parcial', 'Parcialmente Recebido'), ('Concluido', 'Concluído'), ('Cancelado', 'Cancelado')], default='Aberto', max_length=10)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fornecedor', verbose_name='Fornecedor')),
                ('usuario_criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Plano de Compra',
                'verbose_name_plural': 'Planos de Compra',
            },
        ),
        migrations.CreateModel(
            name='ItemPlanoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_prevista', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qtd. Prevista')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('grade_numeracao', models.JSONField(blank=True, null=True, verbose_name='Grade de Numeração')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.material')),
                ('plano_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.planocompra')),
            ],
            options={
                'verbose_name': 'Item do Plano de Compra',
                'verbose_name_plural': 'Itens dos Planos de Compra',
            },
        ),
    ]
