# Generated by Django 5.2.2 on 2025-06-12 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('numero', models.CharField(max_length=50, verbose_name='Número da NF')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão da NF')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total da NF')),
                ('arquivo_xml', models.FileField(blank=True, null=True, upload_to='notas_fiscais/', verbose_name='Arquivo XML')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'unique_together': {('numero', 'fornecedor')},
            },
        ),
        migrations.CreateModel(
            name='ItemNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.material')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_nf', to='core.notafiscal')),
            ],
            options={
                'verbose_name': 'Item da Nota Fiscal',
                'verbose_name_plural': 'Itens das Notas Fiscais',
            },
        ),
        migrations.CreateModel(
            name='Recebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('data_recebimento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Recebimento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('conferente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Conferente')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.notafiscal', verbose_name='Nota Fiscal Vinculada')),
                ('plano_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.planocompra', verbose_name='Plano de Compra Vinculado')),
            ],
            options={
                'verbose_name': 'Recebimento Físico',
                'verbose_name_plural': 'Recebimentos Físicos',
            },
        ),
        migrations.CreateModel(
            name='ItemRecebido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_contada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.material')),
                ('recebimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_recebidos', to='core.recebimento')),
            ],
            options={
                'verbose_name': 'Item Recebido',
                'verbose_name_plural': 'Itens Recebidos',
            },
        ),
    ]
