# Generated by Django 5.2.3 on 2025-06-15 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notafiscal_itemnotafiscal_recebimento_itemrecebido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defeito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Defeito')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Defeito')),
            ],
            options={
                'verbose_name': 'Defeito',
                'verbose_name_plural': 'Defeitos',
            },
        ),
        migrations.CreateModel(
            name='InspecaoQualidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Aprovado com Ressalvas', 'Aprovado com Ressalvas')], default='Pendente', max_length=30)),
                ('observacoes_gerais', models.TextField(blank=True, null=True, verbose_name='Observações Gerais da Inspeção')),
                ('recebimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.recebimento', verbose_name='Recebimento Inspecionado')),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Revisor Responsável')),
            ],
            options={
                'verbose_name': 'Inspeção de Qualidade',
                'verbose_name_plural': 'Inspeções de Qualidade',
            },
        ),
        migrations.CreateModel(
            name='ItemInspecionadoDefeito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('quantidade_defeituosa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade com Defeito')),
                ('defeito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.defeito', verbose_name='Defeito Apontado')),
                ('item_recebido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defeitos_encontrados', to='core.itemrecebido')),
            ],
            options={
                'verbose_name': 'Defeito de Item Inspecionado',
                'verbose_name_plural': 'Defeitos de Itens Inspecionados',
            },
        ),
    ]
